spring.kafka.bootstrap-servers=kafka1:29092,kafka2:29092,kafka3:29092
spring.datasource.url=jdbc:mysql://mysql:3306/wikimedia
spring.datasource.username=kafkaUser
spring.datasource.password=favourite1

